<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-03-26">

<title>IS415–GAA - Take-home Exercise 2: Application of Spatial and Spatio-temporal Analysis Methods to Discover the Distribution of Dengue Fever in Tainan City, Taiwan</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="../../site_libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="../../site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="../../site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="../../site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415–GAA</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">Hands-on Exercise</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html">
 <span class="dropdown-text">Hands-on Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html">
 <span class="dropdown-text">Hands-on Exercise 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex09.html">
 <span class="dropdown-text">Hands-on Exercise 9</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">In-class Exercise</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex02/In-class_Ex02.html">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03.html">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex05.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex07/In-class_Ex07.html">
 <span class="dropdown-text">In-class Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex08/In-class_Ex08.html">
 <span class="dropdown-text">In-class Exercise 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex09/In-class_Ex09.html">
 <span class="dropdown-text">In-class Exercise 9</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">Take-home Exercise</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html">
 <span class="dropdown-text">Take-home Exercise 3</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">1 Introduction</a>
  <ul class="collapse">
  <li><a href="#setting-the-scene" id="toc-setting-the-scene" class="nav-link" data-scroll-target="#setting-the-scene">1.1 Setting the Scene</a></li>
  </ul></li>
  <li><a href="#preparing-the-data" id="toc-preparing-the-data" class="nav-link" data-scroll-target="#preparing-the-data">2 Preparing the data</a>
  <ul class="collapse">
  <li><a href="#loading-the-packages-and-importing-data" id="toc-loading-the-packages-and-importing-data" class="nav-link" data-scroll-target="#loading-the-packages-and-importing-data">2.1 Loading the packages and importing data</a>
  <ul class="collapse">
  <li><a href="#importing-tainan-village-data" id="toc-importing-tainan-village-data" class="nav-link" data-scroll-target="#importing-tainan-village-data">2.1.1 Importing Tainan Village Data</a></li>
  <li><a href="#importing-daily-dengue-data" id="toc-importing-daily-dengue-data" class="nav-link" data-scroll-target="#importing-daily-dengue-data">2.1.2 Importing Daily Dengue Data</a></li>
  </ul></li>
  <li><a href="#preparing-the-geospatial-data" id="toc-preparing-the-geospatial-data" class="nav-link" data-scroll-target="#preparing-the-geospatial-data">2.2 Preparing the Geospatial Data</a></li>
  <li><a href="#preparing-the-aspatial-data" id="toc-preparing-the-aspatial-data" class="nav-link" data-scroll-target="#preparing-the-aspatial-data">2.3 Preparing the Aspatial Data</a></li>
  <li><a href="#combining-the-datasets" id="toc-combining-the-datasets" class="nav-link" data-scroll-target="#combining-the-datasets">2.4 Combining the datasets</a></li>
  </ul></li>
  <li><a href="#spacetime-s3-class" id="toc-spacetime-s3-class" class="nav-link" data-scroll-target="#spacetime-s3-class">3 Spacetime s3 class</a></li>
  <li><a href="#global-spatial-autocorrelation" id="toc-global-spatial-autocorrelation" class="nav-link" data-scroll-target="#global-spatial-autocorrelation">4 Global Spatial Autocorrelation</a>
  <ul class="collapse">
  <li><a href="#deriving-contiguity-weights-queens-method" id="toc-deriving-contiguity-weights-queens-method" class="nav-link" data-scroll-target="#deriving-contiguity-weights-queens-method">4.1 Deriving contiguity weights: Queen’s method</a></li>
  </ul></li>
  <li><a href="#local-spatial-autocorrelation-analysis" id="toc-local-spatial-autocorrelation-analysis" class="nav-link" data-scroll-target="#local-spatial-autocorrelation-analysis">5 Local Spatial Autocorrelation Analysis</a>
  <ul class="collapse">
  <li><a href="#computing-contiguity-spatial-weights" id="toc-computing-contiguity-spatial-weights" class="nav-link" data-scroll-target="#computing-contiguity-spatial-weights">5.1 Computing Contiguity Spatial Weights</a></li>
  <li><a href="#row-standardised-weights-matrix" id="toc-row-standardised-weights-matrix" class="nav-link" data-scroll-target="#row-standardised-weights-matrix">5.2 Row-standardised weights matrix</a>
  <ul class="collapse">
  <li><a href="#mapping-the-local-morans-i" id="toc-mapping-the-local-morans-i" class="nav-link" data-scroll-target="#mapping-the-local-morans-i">5.1.1 Mapping the local Moran’s I</a></li>
  <li><a href="#mapping-local-morans-i-values" id="toc-mapping-local-morans-i-values" class="nav-link" data-scroll-target="#mapping-local-morans-i-values">5.1.2 Mapping local Moran’s I values</a></li>
  <li><a href="#mapping-local-morans-i-p-values" id="toc-mapping-local-morans-i-p-values" class="nav-link" data-scroll-target="#mapping-local-morans-i-p-values">5.1.3 Mapping local Moran’s I p-values</a></li>
  <li><a href="#mapping-both-local-morans-i-values-and-p-values" id="toc-mapping-both-local-morans-i-values-and-p-values" class="nav-link" data-scroll-target="#mapping-both-local-morans-i-values-and-p-values">5.1.4 Mapping both local Moran’s I values and p-values</a></li>
  </ul></li>
  <li><a href="#creating-a-lisa-cluster-map" id="toc-creating-a-lisa-cluster-map" class="nav-link" data-scroll-target="#creating-a-lisa-cluster-map">5.2 Creating a LISA Cluster Map</a>
  <ul class="collapse">
  <li><a href="#plotting-moran-scatterplot" id="toc-plotting-moran-scatterplot" class="nav-link" data-scroll-target="#plotting-moran-scatterplot">5.2.1 Plotting Moran scatterplot</a></li>
  <li><a href="#plotting-moran-scatterplot-with-standardised-variable" id="toc-plotting-moran-scatterplot-with-standardised-variable" class="nav-link" data-scroll-target="#plotting-moran-scatterplot-with-standardised-variable">5.2.2 Plotting Moran scatterplot with standardised variable</a></li>
  <li><a href="#preparing-lisa-map-classes" id="toc-preparing-lisa-map-classes" class="nav-link" data-scroll-target="#preparing-lisa-map-classes">5.2.3 Preparing LISA map classes</a></li>
  <li><a href="#plotting-lisa-map" id="toc-plotting-lisa-map" class="nav-link" data-scroll-target="#plotting-lisa-map">5.2.4 Plotting LISA map</a></li>
  </ul></li>
  <li><a href="#computing-local-morans-i-using-local_moran-function" id="toc-computing-local-morans-i-using-local_moran-function" class="nav-link" data-scroll-target="#computing-local-morans-i-using-local_moran-function">5.3 Computing local Moran’s I (using local_moran() function)</a></li>
  <li><a href="#visualising-local-morans-i" id="toc-visualising-local-morans-i" class="nav-link" data-scroll-target="#visualising-local-morans-i">6.2 Visualising local Moran’s I</a></li>
  </ul></li>
  <li><a href="#emerging-hot-spot-analysis-sfdep-methods" id="toc-emerging-hot-spot-analysis-sfdep-methods" class="nav-link" data-scroll-target="#emerging-hot-spot-analysis-sfdep-methods">6 Emerging Hot Spot Analysis: sfdep methods</a>
  <ul class="collapse">
  <li><a href="#creating-a-time-series-cube" id="toc-creating-a-time-series-cube" class="nav-link" data-scroll-target="#creating-a-time-series-cube">6.1 Creating a Time Series Cube</a></li>
  <li><a href="#computing-gi" id="toc-computing-gi" class="nav-link" data-scroll-target="#computing-gi">6.2 Computing Gi*</a></li>
  <li><a href="#mann-kendall-test" id="toc-mann-kendall-test" class="nav-link" data-scroll-target="#mann-kendall-test">6.3 Mann-Kendall Test</a></li>
  <li><a href="#arrange-to-show-significant-emerging-hotcold-spots" id="toc-arrange-to-show-significant-emerging-hotcold-spots" class="nav-link" data-scroll-target="#arrange-to-show-significant-emerging-hotcold-spots">6.4 Arrange to show significant emerging hot/cold spots</a></li>
  <li><a href="#performing-emerging-hotspot-analysis" id="toc-performing-emerging-hotspot-analysis" class="nav-link" data-scroll-target="#performing-emerging-hotspot-analysis">6.5 Performing Emerging Hotspot Analysis</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 2: Application of Spatial and Spatio-temporal Analysis Methods to Discover the Distribution of Dengue Fever in Tainan City, Taiwan</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 26, 2024</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="introduction" class="level1">
<h1>1 Introduction</h1>
<section id="setting-the-scene" class="level2">
<h2 class="anchored" data-anchor-id="setting-the-scene">1.1 Setting the Scene</h2>
<p>Dengue Hemorrhagic Fever (in short dengue fever) is one of the most widespread mosquito-borne diseases in the most tropical and subtropical regions. It is an acute disease caused by dengue virus infection which is transmitted by female Aedes aegypti and Aedes albopictus mosquitoes. In 2015, Taiwan had recorded the most severe dengue fever outbreak with more than 43,000 dengue cases and 228 deaths. Since then, the annual reported dengue fever cases were maintained at the level of not more than 200 cases.</p>
</section>
</section>
<section id="preparing-the-data" class="level1">
<h1>2 Preparing the data</h1>
<section id="loading-the-packages-and-importing-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-packages-and-importing-data">2.1 Loading the packages and importing data</h2>
<p>The following R packages are used for this assignment:</p>
<ul>
<li><p><strong>sf:</strong> for importing, manipulating and processing geospatial data</p></li>
<li><p><strong>tmap:</strong> to create thematic maps</p></li>
<li><p><strong>tidyverse:</strong> a family of modern R packages specially designed to meet the tasks of Data Science in R</p>
<ul>
<li><strong>tidyr:</strong> an R package for tidying data</li>
<li><strong>dplyr:</strong> a grammer of data manipulation</li>
<li><strong>ggplot2:</strong> a grammar of graphics</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(readxl, sf, tidyverse, tmap, sfdep, gifski, dplyr, lubridate, ggplot2, spdep, plotly)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="importing-tainan-village-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-tainan-village-data">2.1.1 Importing Tainan Village Data</h3>
<p>TAIWAN_VILLAGE_2020: a geospatial data of village boundary of Taiwan. It is in ESRI shapefile format. The data is in Taiwan Geographic Coordinate System.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>tv <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>, <span class="at">layer =</span> <span class="st">"TAINAN_VILLAGE"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `TAINAN_VILLAGE' from data source 
  `/Users/shanellelam/Library/CloudStorage/OneDrive-SingaporeManagementUniversity/School/Year 3/chanelelele/IS415-GAA/Take-home_Ex/Take-home_Ex02/data/geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 649 features and 10 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 120.0269 ymin: 22.88751 xmax: 120.6563 ymax: 23.41374
Geodetic CRS:  TWD97</code></pre>
</div>
</div>
</section>
<section id="importing-daily-dengue-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-daily-dengue-data">2.1.2 Importing Daily Dengue Data</h3>
<p>Dengue_Daily: an aspatial data of reported dengue cases in Taiwan since 1998.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>dengue_daily <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/aspatial/Dengue_Daily.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `Dengue_Daily' from data source 
  `/Users/shanellelam/Library/CloudStorage/OneDrive-SingaporeManagementUniversity/School/Year 3/chanelelele/IS415-GAA/Take-home_Ex/Take-home_Ex02/data/aspatial/Dengue_Daily.csv' 
  using driver `CSV'</code></pre>
</div>
</div>
</section>
</section>
<section id="preparing-the-geospatial-data" class="level2">
<h2 class="anchored" data-anchor-id="preparing-the-geospatial-data">2.2 Preparing the Geospatial Data</h2>
<p>Firstly, to create a thematic map of the Tainan Villages dataset by adding borders to highlight the boundaries of the geographic features.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(tv) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We are only looking to study the villages that are confined to the D01, D02, D04, D06, D07, D08, D32 and D39 counties of Tainan City, Taiwan. Therefore, we are filtering the dataset by the variable TOWNID in order to extract only counties that we are interested in.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(<span class="fu">filter</span>(tv, tv<span class="sc">$</span>TOWNID <span class="sc">==</span> <span class="st">"D01"</span> <span class="sc">|</span> tv<span class="sc">$</span>TOWNID <span class="sc">==</span> <span class="st">"D02"</span> <span class="sc">|</span> tv<span class="sc">$</span>TOWNID <span class="sc">==</span> <span class="st">"D04"</span> <span class="sc">|</span> tv<span class="sc">$</span>TOWNID <span class="sc">==</span> <span class="st">"D06"</span> <span class="sc">|</span> tv<span class="sc">$</span>TOWNID <span class="sc">==</span> <span class="st">"D07"</span> <span class="sc">|</span> tv<span class="sc">$</span>TOWNID <span class="sc">==</span> <span class="st">"D08"</span> <span class="sc">|</span> tv<span class="sc">$</span>TOWNID <span class="sc">==</span> <span class="st">"D32"</span> <span class="sc">|</span> tv<span class="sc">$</span>TOWNID <span class="sc">==</span> <span class="st">"D39"</span>)) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"TOWNID"</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>tv_ids <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"D01"</span>, <span class="st">"D02"</span>, <span class="st">"D04"</span>, <span class="st">"D06"</span>, <span class="st">"D07"</span>, <span class="st">"D08"</span>, <span class="st">"D32"</span>, <span class="st">"D39"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>tv_counties <span class="ot">&lt;-</span> <span class="fu">subset</span>(tv, TOWNID <span class="sc">%in%</span> tv_ids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="preparing-the-aspatial-data" class="level2">
<h2 class="anchored" data-anchor-id="preparing-the-aspatial-data">2.3 Preparing the Aspatial Data</h2>
<p>In order to make data processing more convenient, we are renaming the following columns from Chinese to English:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> dengue_daily <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"Onset_Date"</span> <span class="ot">=</span> <span class="st">"發病日"</span>,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"x-coordinate"</span> <span class="ot">=</span> <span class="st">"最小統計區中心點X"</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"y-coordinate"</span> <span class="ot">=</span> <span class="st">"最小統計區中心點Y"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"village"</span> <span class="ot">=</span> <span class="st">"居住村里"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"town"</span> <span class="ot">=</span> <span class="st">"居住縣市"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I am only looking to study the dengue fever cases that are confined to epidemiology weeks 31-50 in the year 2023. Therefore, the dengue cases dataset is being filtered and extracted according to the time period that we are interested in. However, it is important to note that since the first day of the week in Taiwan is a Sunday, the dates that need to be extracted are as follows: <strong>Week 31 - 50: 30 July 2023 - 16 December 2023</strong></p>
<p>With reference to: http://chartsbin.com/view/41671</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>dd_filter <span class="ot">&lt;-</span> dd <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                <span class="fu">filter</span>(Onset_Date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2023/07/30"</span>) <span class="sc">&amp;</span> Onset_Date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2023/12/16"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The following code block creates a new column in the dataset called <strong>week</strong>, reflecting which week the dengue fever cases belong to.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>dd_filter <span class="ot">&lt;-</span> dd_filter <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">factor</span>(<span class="fu">year</span>(Onset_Date)),</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">week =</span> <span class="fu">week</span>(Onset_Date)) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Onset_Date <span class="sc">&gt;=</span> <span class="st">"2023/07/30"</span> <span class="sc">&amp;</span> Onset_Date <span class="sc">&lt;=</span> <span class="st">"2023/12/16"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="combining-the-datasets" class="level2">
<h2 class="anchored" data-anchor-id="combining-the-datasets">2.4 Combining the datasets</h2>
<p>Next, I merged the two datasets using a left join operation, where the village name columns serve as the key to combine the data from both datasets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>tv_dd <span class="ot">&lt;-</span> <span class="fu">left_join</span>(tv_counties, dd_filter, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"VILLNAME"</span> <span class="ot">=</span> <span class="st">"village"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, I created a new dataframe that groups the tv_dd dataframe by the variable “VILLENG”. It then calculates the count of observations within each group and stores it in a new column named “grp_cnt”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>village_sf <span class="ot">&lt;-</span> tv_dd <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(VILLENG) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">grp_cnt =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows of the new data frame</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(village_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 2 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 120.1926 ymin: 23.01258 xmax: 120.2308 ymax: 23.05601
Geodetic CRS:  TWD97
# A tibble: 6 × 3
  VILLENG     grp_cnt                                                   geometry
  &lt;chr&gt;         &lt;int&gt;                                              &lt;POLYGON [°]&gt;
1 Andong Vil.      83 ((120.2164 23.0404, 120.2154 23.04033, 120.2153 23.04017,…
2 Anfu Vil.       311 ((120.1932 23.0294, 120.1929 23.02938, 120.1926 23.02936,…
3 Anhe Vil.        86 ((120.2258 23.04424, 120.2219 23.03862, 120.2219 23.03862…
4 Ankang Vil.     102 ((120.2269 23.01413, 120.2274 23.01331, 120.2277 23.01289…
5 Anqing Vil.     109 ((120.2113 23.04414, 120.2111 23.04413, 120.2108 23.04413…
6 Anshun Vil.      35 ((120.2136 23.05601, 120.2136 23.05586, 120.2135 23.05531…</code></pre>
</div>
</div>
<p>Next, I created a new dataframe that groups the tv_dd dataframe by the variables “week” and “VILLENG”. Similarly, it calculates the count of observations within each group and stores it in a new column named “grp_cnt”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> tv_dd <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(week, VILLENG) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">grp_cnt =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows of the new data frame</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 3 fields
Geometry type: GEOMETRY
Dimension:     XY
Bounding box:  xmin: 120.1926 ymin: 22.9156 xmax: 120.2585 ymax: 23.0404
Geodetic CRS:  TWD97
# A tibble: 6 × 4
   week VILLENG        grp_cnt                                          geometry
  &lt;dbl&gt; &lt;chr&gt;            &lt;int&gt;                                    &lt;GEOMETRY [°]&gt;
1    31 Andong Vil.          1 POLYGON ((120.2164 23.0404, 120.2154 23.04033, 1…
2    31 Anfu Vil.            1 POLYGON ((120.1932 23.0294, 120.1929 23.02938, 1…
3    31 Ankang Vil.          2 POLYGON ((120.2269 23.01413, 120.2274 23.01331, …
4    31 Bao'an Vil.          1 POLYGON ((120.2304 22.93544, 120.2301 22.93511, …
5    31 Chengde Vil.         3 POLYGON ((120.2036 23.01244, 120.2031 23.01238, …
6    31 Chenggong Vil.      27 MULTIPOLYGON (((120.2388 23.00454, 120.2388 23.0…</code></pre>
</div>
</div>
<p>The first chunk of code creates a new dataframe complete_df using the expand.grid() function, which generates a data frame from all combinations of the supplied vectors or factors. In this case, it creates combinations of weeks ranging from 31 to 50 for each unique village ID (“VILLENG”) extracted from the df dataframe.</p>
<p>Then, it performs a left join with the df dataframe to fill in the grp_cnt values for each combination of week and village ID. Missing values in the grp_cnt column are replaced with 0 using the ifelse() function. Finally, it merges geometry information from the village_sf dataframe based on the VILLENG variable, resulting in the dengue_sf dataframe.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>complete_df <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">week =</span> <span class="dv">31</span><span class="sc">:</span><span class="dv">50</span>, <span class="at">VILLENG =</span> <span class="fu">unique</span>(df<span class="sc">$</span>VILLENG))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Left join with df to fill in grp_cnt values</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>dengue_sf <span class="ot">&lt;-</span> <span class="fu">left_join</span>(complete_df, df, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"week"</span>, <span class="st">"VILLENG"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">grp_cnt =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(grp_cnt), <span class="dv">0</span>, grp_cnt))  <span class="co"># Replace NA values with 0</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge geometry information from village_sf based on VILLENG</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>dengue_sf <span class="ot">&lt;-</span> dengue_sf <span class="sc">%&gt;%</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(<span class="fu">select</span>(village_sf, VILLENG, geometry), <span class="at">by =</span> <span class="st">"VILLENG"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select geometry.y column as geometry and drop geometry.x column</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>dengue_sf <span class="ot">&lt;-</span> dengue_sf <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>geometry.x, <span class="at">geometry =</span> geometry.y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The following code chunk generates a bar plot using ggplot2. It visualizes the number of cases by week.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tv_dd, <span class="fu">aes</span>(<span class="at">x =</span> week)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Number of Cases by Week"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Week"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of Cases"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the bar graph, it indicates an increasing trend from week 30 to week 39. It then reached the highest number of dengue cases outbreak in week 39 before gradually decreasing all the way till week 50.</p>
<p>According to research, this pattern is often seen in infectious disease outbreaks. It suggests that there was a period of heightened transmission leading to the peak of the outbreak, followed by a decline as control measures or natural factors that may mitigate the spread of the disease.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dengue_sf, <span class="fu">aes</span>(<span class="at">x =</span> week, <span class="at">y =</span> grp_cnt)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Number of Cases by Village"</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"VILLENG"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of Cases"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The following code chunk creates a thematic map that displays the distribution of dengue cases by village in Tainan, Taiwan. The color of each village on the map represents the number of dengue cases reported, with darker shades indicating higher case counts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(village_sf) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"grp_cnt"</span>, </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"quantile"</span>, </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Village"</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Distribution of Dengue Cases by Village, Tainan"</span>,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.2</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.60</span>, </span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.50</span>,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span><span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the thematic map, it’s evident that the regions experiencing the highest incidences of dengue outbreaks are concentrated in the central and southern areas of our study area. This spatial pattern suggests a clustering of dengue cases in specific geographic locations rather than a uniform distribution across the entire area.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>equal <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(tv_dd) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"VILLENG"</span>,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">n =</span> <span class="dv">5</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"equal"</span>) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Equal interval classification"</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>quantile <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(tv_dd) <span class="sc">+</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"VILLENG"</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">n =</span> <span class="dv">5</span>,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Equal quantile classification"</span>)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(equal, </span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>             quantile, </span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">asp=</span><span class="dv">1</span>, </span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="spacetime-s3-class" class="level1">
<h1>3 Spacetime s3 class</h1>
<p>The spacetime class links a dataframe and an sf object based on a shared location identifier column. These are referred to as the data context and the geometry context.</p>
<p>Four important aspects to the spacetime class:</p>
<ul>
<li><p>the data: dd (a dataframe object)</p></li>
<li><p>the geometry: tv_counties (an sf object)</p></li>
<li><p>the location identifiers:</p></li>
<li><p>the time column:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>spt <span class="ot">&lt;-</span> sfdep<span class="sc">::</span><span class="fu">spacetime</span>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">.data =</span> dengue_sf,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">.geometry =</span> village_sf,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">.loc_col =</span> <span class="st">"VILLNAME"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">.time_col =</span> <span class="st">"week"</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert polygons/multipolygons to points</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>spt<span class="sc">$</span>geometry_point <span class="ot">&lt;-</span> <span class="fu">st_centroid</span>(spt<span class="sc">$</span>geometry)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="global-spatial-autocorrelation" class="level1">
<h1>4 Global Spatial Autocorrelation</h1>
<p>Spatial autocorrelation is the term used to describe the presence of systematic spatial variation in a variable.</p>
<p><strong>Hypotheses:</strong></p>
<ul>
<li><p><strong>Null Hypothesis:</strong> The map suggests that the outbreak of dengue cases occurred randomly over space. (complete spatial randomness)</p></li>
<li><p><strong>Alternative Hypothesis:</strong> The map suggests that the outbreak of dengue cases occurred in a non-random pattern over space (spatially clustered)</p></li>
</ul>
<section id="deriving-contiguity-weights-queens-method" class="level2">
<h2 class="anchored" data-anchor-id="deriving-contiguity-weights-queens-method">4.1 Deriving contiguity weights: Queen’s method</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>wm_q <span class="ot">&lt;-</span> village_sf <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_contiguity</span>(geometry),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">wt =</span> <span class="fu">st_weights</span>(nb,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">style =</span> <span class="st">"W"</span>),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>wm_q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 249 features and 4 fields
Geometry type: GEOMETRY
Dimension:     XY
Bounding box:  xmin: 120.0627 ymin: 22.89401 xmax: 120.2925 ymax: 23.09144
Geodetic CRS:  TWD97
# A tibble: 249 × 5
   nb        wt        VILLENG     grp_cnt                              geometry
 * &lt;nb&gt;      &lt;list&gt;    &lt;chr&gt;         &lt;int&gt;                         &lt;POLYGON [°]&gt;
 1 &lt;int [5]&gt; &lt;dbl [5]&gt; Andong Vil.      83 ((120.2164 23.0404, 120.2154 23.0403…
 2 &lt;int [5]&gt; &lt;dbl [5]&gt; Anfu Vil.       311 ((120.1932 23.0294, 120.1929 23.0293…
 3 &lt;int [7]&gt; &lt;dbl [7]&gt; Anhe Vil.        86 ((120.2258 23.04424, 120.2219 23.038…
 4 &lt;int [3]&gt; &lt;dbl [3]&gt; Ankang Vil.     102 ((120.2269 23.01413, 120.2274 23.013…
 5 &lt;int [4]&gt; &lt;dbl [4]&gt; Anqing Vil.     109 ((120.2113 23.04414, 120.2111 23.044…
 6 &lt;int [3]&gt; &lt;dbl [3]&gt; Anshun Vil.      35 ((120.2136 23.05601, 120.2136 23.055…
 7 &lt;int [8]&gt; &lt;dbl [8]&gt; Anxi Vil.       141 ((120.2123 23.03689, 120.212 23.0368…
 8 &lt;int [5]&gt; &lt;dbl [5]&gt; Bao'an Vil.      33 ((120.2304 22.93544, 120.2301 22.935…
 9 &lt;int [6]&gt; &lt;dbl [6]&gt; Beihua Vil.       1 ((120.2034 23.00257, 120.2032 23.002…
10 &lt;int [4]&gt; &lt;dbl [4]&gt; Beimen Vil.       8 ((120.2176 23.02032, 120.2173 23.020…
# ℹ 239 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">global_moran_test</span>(wm_q<span class="sc">$</span>grp_cnt,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>nb,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>wt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  x  
weights: listw    

Moran I statistic standard deviate = 8.6483, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
      0.309827683      -0.004032258       0.001317068 </code></pre>
</div>
</div>
<p>From the Moran I test, the statistic standard deviate value (z-value) is 8.6483. This value represents the number of standard deviations the observed Moran’s I statistic deviates from the expected value under the null hypothesis of spatial randomness.</p>
<p>Therefore, the z-value of 8.6483 and a very low p-value (&lt; 2.2e-16), there is strong evidence to reject the null hypothesis of spatial randomness. This suggests that the outbreaks are not randomly distributed but rather exhibit spatial clustering, where areas with high dengue activity tend to be geographically close to each other.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The following code chunk uses the global_moran_perm function that computes the global Moran’s I statistic for spatial autocorrelation using permutation tests. This function conducts a permutation test to assess the significance of the Moran’s I statistic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">global_moran_perm</span>(wm_q<span class="sc">$</span>grp_cnt,</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>nb,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>wt,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">nsim =</span> <span class="dv">99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  x 
weights: listw  
number of simulations + 1: 100 

statistic = 0.30983, observed rank = 100, p-value &lt; 2.2e-16
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<p>The calculated p-value of &lt; 2.2e-16 indicates a strong evidence against the null hypothesis of spatial randomness. Therefore, suggesting that there is a significant spatial autocorrelation present in the data.</p>
</section>
</section>
<section id="local-spatial-autocorrelation-analysis" class="level1">
<h1>5 Local Spatial Autocorrelation Analysis</h1>
<section id="computing-contiguity-spatial-weights" class="level2">
<h2 class="anchored" data-anchor-id="computing-contiguity-spatial-weights">5.1 Computing Contiguity Spatial Weights</h2>
<p>The following code chunk uses the poly2nb() function of the spdep package to compute contiguity weight matrices for the study area. This function builds a neighbours list based on regions with contiguous boundaries. Therefore, it computes the Queen contiguity weight matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>wm_q2 <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(village_sf, </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">queen=</span><span class="cn">TRUE</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_q2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 249 
Number of nonzero links: 1522 
Percentage nonzero weights: 2.454799 
Average number of links: 6.11245 
Link number distribution:

 2  3  4  5  6  7  8  9 10 11 12 13 22 
 4 15 43 47 46 38 26 13  7  6  2  1  1 
4 least connected regions:
72 81 84 243 with 2 links
1 most connected region:
19 with 22 links</code></pre>
</div>
</div>
<p>The summary report above shows that there are 249 area units in our Tainan study area. The most connected area unit has 22 neighbours. There are 4 area units with only 2 neighbours.</p>
</section>
<section id="row-standardised-weights-matrix" class="level2">
<h2 class="anchored" data-anchor-id="row-standardised-weights-matrix">5.2 Row-standardised weights matrix</h2>
<p>The following code chunk assigns weights to each neighbouring polygon. he nb2listw function is used to create this matrix, specifying the style as “W” for equal weighting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>rswm_q <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_q2, </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">style=</span><span class="st">"W"</span>, </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The following code chunk computes local Moran’s I statistics for the variable grp_cnt in the dataset village_sf, using the spatial weights matrix rswm_q previously generated. The local moran’s I statistic is computed using the localmoran() function directly from the spdep package. This function calculates local Moran’s I without the need for explicitly defining a spatial weights matrix. Instead, it derives the spatial weights internally based on the neighborhood structure specified by nb.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>fips <span class="ot">&lt;-</span> <span class="fu">order</span>(village_sf<span class="sc">$</span>VILLENG)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>localMI <span class="ot">&lt;-</span> <span class="fu">localmoran</span>(village_sf<span class="sc">$</span>grp_cnt, rswm_q)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(localMI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Ii          E.Ii      Var.Ii      Z.Ii Pr(z != E(Ii))
1 0.06678456 -9.831024e-05 0.004816092 0.9637569      0.3351678
2 2.72035266 -4.184340e-02 1.964274101 1.9708495      0.0487411
3 0.01294335 -1.556562e-04 0.005401571 0.1782289      0.8585432
4 0.26530641 -6.830524e-04 0.056195885 1.1220499      0.2618412
5 0.22172647 -1.031123e-03 0.063342426 0.8850854      0.3761106
6 0.23051374 -9.648473e-04 0.079357246 0.8217080      0.4112431</code></pre>
</div>
</div>
<p>The following code chunk prints the local Moran’s I statistics calculated earlier in a formatted coefficient matrix. It arranges the statistics corresponding to each village (VILLENG) in the same order as the fips variable, which represents the sorted order of villages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">printCoefmat</span>(<span class="fu">data.frame</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  localMI[fips,], </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names=</span>village_sf<span class="sc">$</span>VILLENG[fips]),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         Ii        E.Ii      Var.Ii        Z.Ii Pr.z....E.Ii..
Andong Vil.      6.6785e-02 -9.8310e-05  4.8161e-03  9.6376e-01         0.3352
Anfu Vil.        2.7204e+00 -4.1843e-02  1.9643e+00  1.9708e+00         0.0487
Anhe Vil.        1.2943e-02 -1.5566e-04  5.4016e-03  1.7823e-01         0.8585
Ankang Vil.      2.6531e-01 -6.8305e-04  5.6196e-02  1.1220e+00         0.2618
Anqing Vil.      2.2173e-01 -1.0311e-03  6.3342e-02  8.8509e-01         0.3761
Anshun Vil.      2.3051e-01 -9.6485e-04  7.9357e-02  8.2171e-01         0.4112
Anxi Vil.        5.5348e-01 -3.5318e-03  1.0644e-01  1.7073e+00         0.0878
Bao'an Vil.     -3.9417e-01 -1.0738e-03  5.2554e-02 -1.7147e+00         0.0864
Beihua Vil.      3.3566e-01 -3.6105e-03  1.4627e-01  8.8709e-01         0.3750
Beimen Vil.     -2.7340e-01 -2.9281e-03  1.7953e-01 -6.3833e-01         0.5233
Beiwan Vil.      5.0771e-01 -2.2356e-03  1.8364e-01  1.1900e+00         0.2341
Beixing Vil.     4.2059e-01 -2.5702e-03  1.2560e-01  1.1940e+00         0.2325
Budai Vil.       2.5596e-01 -8.6169e-04  4.2181e-02  1.2505e+00         0.2111
Chang'an Vil.    4.2479e-01 -1.5012e-03  7.3438e-02  1.5731e+00         0.1157
Chengbei Vil.    7.0476e-01 -3.1158e-03  1.9100e-01  1.6197e+00         0.1053
Chengda Vil.    -5.8798e-03 -1.7251e-04  5.2165e-03 -7.9021e-02         0.9370
Chengde Vil.    -1.6149e-01 -2.8038e-04  1.1397e-02 -1.5100e+00         0.1310
Chengdong Vil.   7.1054e-01 -3.2118e-03  1.3017e-01  1.9783e+00         0.0479
Chenggong Vil.   1.6369e+00 -1.8779e-01  1.5795e+00  1.4519e+00         0.1465
Chenghuang Vil.  1.4908e-01 -3.6105e-03  1.4627e-01  3.9924e-01         0.6897
Chengnan Vil.    7.1411e-01 -2.4843e-03  8.6011e-02  2.4434e+00         0.0145
Chengxi Vil.     6.9702e-01 -2.4843e-03  2.0402e-01  1.5486e+00         0.1215
Chengzhong Vil.  8.1684e-01 -3.5086e-03  2.1500e-01  1.7692e+00         0.0769
Chihkan Vil.    -3.2227e-01 -1.1437e-03  3.4549e-02 -1.7277e+00         0.0840
Chongcheng Vil. -1.5001e-01 -2.7388e-04  1.3415e-02 -1.2928e+00         0.1961
Chongde Vil.     9.4061e-01 -1.1869e-02  4.7685e-01  1.3793e+00         0.1678
Chonghui Vil.    3.0609e-02 -2.2612e-04  9.1920e-03  3.2162e-01         0.7477
Chongming Vil.  -8.6086e-02 -3.0286e-04  9.1567e-03 -8.9646e-01         0.3700
Chongshan Vil.   1.3557e+00 -7.5251e-03  1.7919e-01  3.2203e+00         0.0013
Chongwen Vil.    7.5816e-02 -2.2612e-04  1.1076e-02  7.2255e-01         0.4700
Chongxin Vil.    9.2532e-01 -3.4311e-03  1.0341e-01  2.8881e+00         0.0039
Chongxue Vil.    5.4445e-01 -2.0949e-03  7.2556e-02  2.0290e+00         0.0425
Da'an Vil.       1.4679e+00 -3.9494e-03  1.3653e-01  3.9834e+00         0.0001
Da'en Vil.       1.1660e-01 -4.2255e-05  1.1311e-03  3.4682e+00         0.0005
Dacheng Vil.     4.6364e-02 -1.3093e-03  5.3166e-02  2.0676e-01         0.8362
Dade Vil.        5.2239e-02 -4.6965e-04  2.8867e-02  3.1023e-01         0.7564
Dafeng Vil.     -6.7934e-02 -5.9672e-04  1.8036e-02 -5.0140e-01         0.6161
Dafu Vil.        4.9666e-02 -9.6485e-04  3.9193e-02  2.5575e-01         0.7981
Dagang Vil.     -5.0970e-03 -5.9672e-04  2.9218e-02 -2.6328e-02         0.9790
Daguang Vil.     2.8296e-01 -3.6105e-03  1.2486e-01  8.1100e-01         0.4174
Dahe Vil.        1.0758e-01 -1.1597e-04  4.0245e-03  1.6976e+00         0.0896
Dajia Vil.      -9.7380e-01 -2.8364e-03  1.7393e-01 -2.3282e+00         0.0199
Daliang Vil.     1.7525e-01 -1.0738e-03  3.2441e-02  9.7897e-01         0.3276
Dalin Vil.       1.8783e-01 -1.1305e-03  4.5914e-02  8.8183e-01         0.3779
Daqiao Vil.      6.4323e-01 -6.5240e-03  2.2495e-01  1.3699e+00         0.1707
Datong Vil.     -2.5248e-02 -1.3508e-04  4.0848e-03 -3.9293e-01         0.6944
Dawan Vil.       3.6610e-01 -1.4358e-03  8.8164e-02  1.2378e+00         0.2158
Daxing Vil.      5.4133e-01 -3.6105e-03  1.4627e-01  1.4248e+00         0.1542
Daxue Vil.      -6.8137e-02 -5.8721e-04  1.5711e-02 -5.3892e-01         0.5899
Dazhi Vil.       2.4606e-01 -9.8310e-05  4.8161e-03  3.5470e+00         0.0004
Dazhong Vil.    -2.2462e-02 -2.2973e-05  1.4127e-03 -5.9702e-01         0.5505
Degao Vil.       4.3656e-01 -1.0311e-03  5.0466e-02  1.9479e+00         0.0514
Deguang Vil.     4.0789e-01 -1.5836e-03  7.7463e-02  1.4712e+00         0.1412
Diandong Vil.    3.9982e-01 -1.7062e-03  6.9256e-02  1.5258e+00         0.1271
Dianxi Vil.      4.9371e-01 -2.4843e-03  1.2141e-01  1.4240e+00         0.1544
Ding'an Vil.     1.5477e-01 -1.7224e-03  5.9677e-02  6.4061e-01         0.5218
Dong'an Vil.     1.0873e-03 -1.4358e-03  8.8164e-02  8.4975e-03         0.9932
Dongguang Vil.   7.1410e-02 -5.4083e-05  1.6355e-03  1.7671e+00         0.0772
Donghe Vil.      1.7051e-01 -2.0771e-03  7.1939e-02  6.4346e-01         0.5199
Dongmen Vil.     9.8319e-02 -1.7062e-03  5.9117e-02  4.1139e-01         0.6808
Dongming Vil.    6.0057e-02 -2.2612e-04  1.3902e-02  5.1128e-01         0.6092
Dongqiao Vil.    2.3066e-01 -1.3235e-03  3.5383e-02  1.2333e+00         0.2175
Dongsheng Vil.   2.8716e-01 -8.7320e-04  3.0280e-02  1.6553e+00         0.0979
Dongwan Vil.     3.2447e-01 -1.6364e-03  1.0046e-01  1.0288e+00         0.3036
Dongxing Vil.    1.0034e-01 -5.4083e-05  2.1989e-03  2.1410e+00         0.0323
Dongzhi Vil.    -2.2047e-01 -1.1180e-04  3.3807e-03 -3.7900e+00         0.0002
Duiyue Vil.      5.0316e-01 -3.6105e-03  1.4627e-01  1.3250e+00         0.1852
Erwang Vil.      1.4918e+00 -9.9107e-03  3.9898e-01  2.3775e+00         0.0174
Erxing Vil.     -1.4066e+00 -2.4000e-03  1.9711e-01 -3.1627e+00         0.0016
Fahua Vil.       1.6709e-01 -8.6169e-04  5.2943e-02  7.2992e-01         0.4654
Fenghuang Vil.   2.0491e-01 -6.9443e-03  4.2407e-01  3.2533e-01         0.7449
Fotan Vil.       2.5072e-01 -4.3338e-04  5.3714e-02  1.0837e+00         0.2785
Fude Vil.        1.5134e-01 -2.5702e-03  8.8975e-02  5.1597e-01         0.6059
Fuguo Vil.       1.1371e+00 -4.7362e-03  1.6360e-01  2.8230e+00         0.0048
Fuhua Vil.       2.4437e+00 -6.1975e-02  3.5749e+00  1.3252e+00         0.1851
Funan Vil.       1.1060e-01 -1.2817e-02  5.1445e-01  1.7207e-01         0.8634
Fuqian Vil.      8.1399e-01 -3.6105e-03  1.7625e-01  1.9475e+00         0.0515
Fuqiang Vil.     1.2501e+00 -1.1317e-02  2.9954e-01  2.3048e+00         0.0212
Fuxing Vil.      1.4060e+00 -8.5548e-02  1.6991e+00  1.1443e+00         0.2525
Fuyu Vil.       -4.6001e-03 -1.0833e-07  5.3074e-06 -1.9967e+00         0.0459
Gongqin Vil.     5.7950e-01 -3.4082e-03  4.2117e-01  8.9820e-01         0.3691
Gongwen Vil.     5.8869e-01 -2.9281e-03  1.7953e-01  1.3963e+00         0.1626
Gongyuan Vil.   -7.8937e-03 -1.8996e-06  7.7236e-05 -8.9798e-01         0.3692
Guangfu Vil.    -1.5788e+00 -2.4843e-03  3.0728e-01 -2.8437e+00         0.0045
Guangming Vil.  -5.1216e-02 -3.0427e-03  1.8654e-01 -1.1154e-01         0.9112
Guangxian Vil.  -2.2482e-02 -8.2110e-05  6.7594e-03 -2.7245e-01         0.7853
Guangzhou Vil.  -3.9460e-03 -1.3991e-06  4.8558e-05 -5.6607e-01         0.5713
Guansheng Vil.  -1.8188e-02 -1.5566e-04  9.5704e-03 -1.8432e-01         0.8538
Guo'an Vil.      2.5554e-01 -9.7703e-04  4.7821e-02  1.1730e+00         0.2408
Guoping Vil.     3.2113e-02 -6.4198e-05  1.3943e-03  8.6174e-01         0.3888
Guozhai Vil.     1.4877e-01 -2.5039e-03  8.6685e-02  5.1380e-01         0.6074
Haidian Vil.     1.8912e+00 -1.4206e-02  5.6940e-01  2.5251e+00         0.0116
Haidong Vil.     2.2361e-01 -4.0640e-04  1.0875e-02  2.1482e+00         0.0317
Hainan Vil.      1.6423e-02 -3.9856e-04  9.5588e-03  1.7205e-01         0.8634
Haixi Vil.      -5.9663e-02 -9.1254e-04  3.1643e-02 -3.3027e-01         0.7412
Heping Vil.      7.2733e-01 -1.0867e-03  5.3182e-02  3.1586e+00         0.0016
Heshun Vil.     -9.6672e-02 -9.8310e-05  3.9969e-03 -1.5276e+00         0.1266
Hexing Vil.     -2.8292e-01 -3.6105e-03  1.0880e-01 -8.4678e-01         0.3971
Houbi Vil.      -4.2893e-01 -7.1789e-04  3.5147e-02 -2.2841e+00         0.0224
Houjia Vil.      8.1489e-01 -3.1376e-03  7.5044e-02  2.9862e+00         0.0028
Huade Vil.      -1.4342e+00 -3.6105e-03  1.0880e-01 -4.3372e+00         0.0000
Huaping Vil.     1.3846e-02 -5.1246e-05  3.1512e-03  2.4756e-01         0.8045
Huwei Vil.       2.3576e+00 -6.5240e-03  3.9857e-01  3.7446e+00         0.0002
Jiading Vil.     3.3106e-01 -4.4155e-04  1.0589e-02  3.2214e+00         0.0013
Jianguo Vil.    -4.4282e-01 -1.3718e-03  4.7546e-02 -2.0245e+00         0.0429
Jiannan Vil.     1.0371e+00 -1.2055e-02  4.1337e-01  1.6318e+00         0.1027
Jianping Vil.    5.4588e-02 -1.1180e-04  4.5452e-03  8.1136e-01         0.4172
Jincheng Vil.    4.3049e-01 -1.2482e-03  5.0690e-02  1.9176e+00         0.0552
Jinhua Vil.      2.4266e-01 -7.0873e-03  3.4477e-01  4.2533e-01         0.6706
Junnan Vil.      1.0485e+00 -3.1376e-03  1.5324e-01  2.6865e+00         0.0072
Junwang Vil.     1.6687e-01 -1.0738e-03  4.3615e-02  8.0416e-01         0.4213
Kainan Vil.     -7.8113e-02 -1.2621e-03  6.1756e-02 -3.0925e-01         0.7571
Kaishan Vil.     1.1894e-02 -4.1474e-06  2.0319e-04  8.3467e-01         0.4039
Kaiyuan Vil.     7.0847e-02 -3.6520e-04  1.1041e-02  6.7772e-01         0.4979
Kunshan Vil.    -7.4293e-02 -1.1597e-04  5.6810e-03 -9.8413e-01         0.3250
Kunshen Vil.    -1.9713e-02 -2.0771e-03  7.1939e-02 -6.5753e-02         0.9476
Liren Vil.       5.4647e-01 -3.6105e-03  1.2486e-01  1.5568e+00         0.1195
Liuhe Vil.       3.6745e-01 -1.5836e-03  4.2326e-02  1.7938e+00         0.0729
Lixiang Vil.     3.5979e-01 -1.7224e-03  1.4156e-01  9.6085e-01         0.3366
Lixing Vil.      2.2145e-02 -4.9815e-06  3.0633e-04  1.2655e+00         0.2057
Longpu Vil.      4.6796e-01 -3.6105e-03  1.7625e-01  1.1233e+00         0.2613
Longshan Vil.    4.7100e-02 -5.4083e-05  1.1746e-03  1.3758e+00         0.1689
Longtan Vil.     3.3876e-01 -7.1789e-04  2.9169e-02  1.9877e+00         0.0468
Lu'er Vil.       8.0127e-01 -3.6105e-03  1.7625e-01  1.9172e+00         0.0552
Ludong Vil.     -1.1460e-01 -1.3718e-03  6.7117e-02 -4.3705e-01         0.6621
Meihua Vil.      3.1187e-01 -4.7816e-04  1.4454e-02  2.5980e+00         0.0094
Mingde Vil.     -1.4902e-01 -2.0000e-03  6.0364e-02 -5.9841e-01         0.5496
Mingliang Vil.   1.3050e+00 -1.0427e-02  6.3452e-01  1.6514e+00         0.0987
Mingxing Vil.    1.0428e+00 -9.4074e-03  3.7890e-01  1.7093e+00         0.0874
Nanchang Vil.    3.6747e-01 -3.6105e-03  1.4627e-01  9.7024e-01         0.3319
Nandou Vil.      7.9039e-02 -3.1885e-05  1.2964e-03  2.1961e+00         0.0281
Nanhua Vil.      1.6823e-01 -2.1738e-03  7.5282e-02  6.2106e-01         0.5346
Nanmei Vil.      5.5738e-01 -3.6105e-03  1.2486e-01  1.5876e+00         0.1124
Nanmen Vil.      5.9009e-01 -3.6105e-03  1.2486e-01  1.6802e+00         0.0929
Nansheng Vil.   -6.6009e-02 -2.4635e-04  1.5145e-02 -5.3437e-01         0.5931
Nanwan Vil.      2.1023e-01 -1.9243e-03  1.1811e-01  6.1731e-01         0.5370
Nanxing Vil.     3.7492e-01 -7.6437e-04  3.1055e-02  2.1318e+00         0.0330
Niaosong Vil.    3.0131e-01 -2.6575e-03  7.0953e-02  1.1412e+00         0.2538
Ping'an Vil.     7.5623e-02 -1.5082e-04  3.6180e-03  1.2598e+00         0.2078
Pingtong Vil.   -1.5277e-02 -9.5211e-06  3.8712e-04 -7.7597e-01         0.4378
Puyuan Vil.      2.8847e-02 -2.1138e-05  1.2998e-03  8.0070e-01         0.4233
Qiancao Vil.     4.5811e-01 -3.6105e-03  1.0880e-01  1.3998e+00         0.1616
Qingcao Vil.     7.7818e-01 -3.5086e-03  2.8785e-01  1.4570e+00         0.1451
Quannan Vil.     5.7460e-02 -1.8670e-03  7.5771e-02  2.1553e-01         0.8294
Ren'ai Vil.      1.2780e+00 -1.2055e-02  2.5868e-01  2.5364e+00         0.0112
Rende Vil.       6.0903e-01 -9.2439e-04  1.8310e-02  4.5077e+00         0.0000
Renhe Vil.       3.3426e+00 -1.7422e-02  5.9414e-01  4.3591e+00         0.0000
Renyi Vil.      -2.1060e-01 -6.1169e-03  5.0051e-01 -2.8904e-01         0.7726
Sanhe Vil.       1.4306e-02 -2.7516e-07  1.3481e-05  3.8963e+00         0.0001
Sanmin Vil.      6.0195e-01 -2.8364e-03  1.3857e-01  1.6247e+00         0.1042
Shalun Vil.      7.9803e-01 -3.5086e-03  2.1500e-01  1.7286e+00         0.0839
Shangding Vil.  -6.0759e-02 -1.3058e-04  3.9486e-03 -9.6485e-01         0.3346
Shanglun Vil.    3.7539e-01 -1.2482e-03  6.1079e-02  1.5240e+00         0.1275
Shenggong Vil.  -8.4659e-01 -2.0000e-03  9.7790e-02 -2.7008e+00         0.0069
Shengli Vil.     3.1238e+00 -2.5109e-02  7.4029e-01  3.6598e+00         0.0003
Shenzhou Vil.   -2.1149e+00 -2.4843e-03  1.2141e-01 -6.0624e+00         0.0000
Shuang'an Vil.   5.4429e-01 -3.6105e-03  1.7625e-01  1.3051e+00         0.1919
Sicao Vil.       5.9539e-01 -3.3093e-03  2.0283e-01  1.3294e+00         0.1837
Song'an Vil.     4.8872e-01 -2.1556e-03  1.7708e-01  1.1665e+00         0.2434
Taizi Vil.       9.2004e-02 -9.1254e-04  2.4407e-02  5.9475e-01         0.5520
Tianfei Vil.     3.8655e-01 -3.6105e-03  1.4627e-01  1.0201e+00         0.3077
Tianliao Vil.    2.6168e-02 -4.2255e-05  2.0701e-03  5.7607e-01         0.5646
Tong'an Vil.     5.4080e-01 -2.5702e-03  1.2560e-01  1.5332e+00         0.1252
Tuku Vil.        1.9670e-01 -2.0771e-03  1.7064e-01  4.8119e-01         0.6304
Wangcheng Vil.   4.7560e-01 -3.6105e-03  2.2122e-01  1.0188e+00         0.3083
Wangliao Vil.   -1.2673e-01 -1.1180e-04  3.3807e-03 -2.1778e+00         0.0294
Wangxing Vil.    6.5926e-01 -3.1158e-03  1.5218e-01  1.6980e+00         0.0895
Weiguo Vil.      7.6092e-03 -6.7288e-04  4.1350e-02  4.0729e-02         0.9675
Weixia Vil.      3.4263e-01 -1.7775e-03  8.6929e-02  1.1681e+00         0.2428
Wencheng Vil.    9.1354e-02 -1.5082e-04  4.5605e-03  1.3550e+00         0.1754
Wenhua Vil.     -1.3154e-02 -9.5211e-06  5.8548e-04 -5.4323e-01         0.5870
Wennan Vil.     -5.8995e-02 -6.3916e-04  1.3874e-02 -4.9544e-01         0.6203
Wenping Vil.    -4.4350e-03 -4.9815e-06  2.4406e-04 -2.8357e-01         0.7767
Wensheng Vil.   -7.2354e-02 -5.1246e-05  1.5498e-03 -1.8366e+00         0.0663
Wenxian Vil.    -1.2071e+00 -3.3093e-03  2.0283e-01 -2.6730e+00         0.0075
Wenyuan Vil.     1.6260e-01 -1.7769e-04  6.1659e-03  2.0729e+00         0.0382
Wutiaogang Vil.  4.6106e-01 -3.6105e-03  1.2486e-01  1.3150e+00         0.1885
Wuwang Vil.      1.2755e+00 -1.2244e-02  4.9173e-01  1.8364e+00         0.0663
Wuzhu Vil.       6.1057e-01 -2.5702e-03  1.5764e-01  1.5443e+00         0.1225
Xianbei Vil.    -1.8740e-02 -5.1246e-05  3.1512e-03 -3.3291e-01         0.7392
Xiangong Vil.    7.2013e-01 -3.6105e-03  9.6306e-02  2.3322e+00         0.0197
Xiaobei Vil.     3.3778e-01 -3.6105e-03  1.4627e-01  8.9263e-01         0.3721
Xiaodong Vil.    4.6359e-02 -7.7521e-04  4.7634e-02  2.1596e-01         0.8290
Xiaoximen Vil.   5.5193e-01 -3.6105e-03  1.2486e-01  1.5722e+00         0.1159
Xibei Vil.       1.1326e-01 -9.7703e-04  2.3419e-02  7.4648e-01         0.4554
Xiding Vil.      1.1117e+00 -2.6776e-03  9.2685e-02  3.6603e+00         0.0003
Xidong Vil.      1.5678e+00 -9.9107e-03  1.7882e-01  3.7309e+00         0.0002
Xihe Vil.        1.9149e-01 -3.6105e-03  9.6306e-02  6.2867e-01         0.5296
Xihu Vil.       -1.3611e-02 -3.1885e-05  1.2964e-03 -3.7715e-01         0.7061
Xinan Vil.      -4.0332e-01 -3.2118e-03  2.6357e-01 -7.7935e-01         0.4358
Xinchang Vil.   -2.0503e-02 -9.5211e-06  5.8548e-04 -8.4697e-01         0.3970
Xindong Vil.    -9.1323e-04 -1.8670e-03  6.4678e-02  3.7504e-03         0.9970
Xingfu Vil.      1.8703e+00 -2.1715e-02  8.6375e-01  2.0357e+00         0.0418
Xingnong Vil.   -4.3980e-01 -1.5012e-03  7.3438e-02 -1.6174e+00         0.1058
Xinsheng Vil.    1.5104e-01 -5.0738e-04  1.7601e-02  1.1423e+00         0.2533
Xinshu Vil.      6.3681e-01 -3.1158e-03  1.9100e-01  1.4642e+00         0.1431
Xinshun Vil.    -1.4866e-03 -2.7516e-07  7.3662e-06 -5.4762e-01         0.5840
Xintian Vil.    -1.3875e-01 -2.3171e-03  1.4215e-01 -3.6185e-01         0.7175
Xinxing Vil.    -3.2313e-02 -2.0117e-04  6.0829e-03 -4.1172e-01         0.6805
Xiqi Vil.        3.1236e+00 -2.3251e-02  7.8820e-01  3.5445e+00         0.0004
Xiqiao Vil.      4.8385e-03 -4.9815e-06  1.5066e-04  3.9461e-01         0.6931
Xishi Vil.       4.8610e-01 -1.7062e-03  8.3451e-02  1.6886e+00         0.0913
Xiwan Vil.       1.2090e-01 -3.0286e-04  1.0508e-02  1.1824e+00         0.2371
Xixian Vil.      5.6346e-02 -1.5082e-04  5.2337e-03  7.8094e-01         0.4348
Xixin Vil.       3.2821e-02 -2.1138e-05  8.5944e-04  1.1203e+00         0.2626
Xuedong Vil.     6.1176e-01 -2.6575e-03  2.1820e-01  1.3153e+00         0.1884
Yancheng Vil.   -8.6157e-01 -3.6105e-03  9.6306e-02 -2.7646e+00         0.0057
Yantian  Vil.    4.3668e-01 -2.6575e-03  8.0156e-02  1.5518e+00         0.1207
Yanxing  Vil.   -6.2464e-03 -4.9815e-06  2.0255e-04 -4.3855e-01         0.6610
Yanxing Vil.     4.3743e-01 -3.6105e-03  2.2122e-01  9.3771e-01         0.3484
Yanzhou  Vil.    9.5479e-02 -2.2028e-04  8.9546e-03  1.0113e+00         0.3119
Yaowang Vil.    -7.4566e-01 -2.5039e-03  1.5359e-01 -1.8963e+00         0.0579
Yijia Vil.      -1.7014e-02 -2.2028e-04  1.0790e-02 -1.6167e-01         0.8716
Yiping Vil.      2.4834e-02 -1.9567e-04  9.5846e-03  2.5566e-01         0.7982
Yizai Vil.       2.4378e-01 -1.5012e-03  6.0947e-02  9.9356e-01         0.3204
Yonghua Vil.    -3.5908e-02 -2.2973e-05  9.3406e-04 -1.1741e+00         0.2403
Yongkang Vil.    5.3655e-02 -5.4657e-04  1.1865e-02  4.9760e-01         0.6188
Yongming Vil.    5.4875e-01 -3.6105e-03  2.2122e-01  1.1744e+00         0.2402
Yongning Vil.    6.2499e-01 -3.1158e-03  1.9100e-01  1.4372e+00         0.1507
Yongxiang Vil.  -3.6215e-01 -1.7940e-03  8.7736e-02 -1.2166e+00         0.2238
Yuanbao Vil.     1.6498e-02 -5.1246e-05  3.1512e-03  2.9481e-01         0.7681
Yuandian Vil.   -1.8974e-02 -1.9243e-03  6.6660e-02 -6.6038e-02         0.9473
Yuandong Vil.    3.3128e-01 -1.5012e-03  7.3438e-02  1.2280e+00         0.2194
Yuanmei Vil.     1.2303e-01 -3.6105e-03  1.2486e-01  3.5840e-01         0.7200
Yuanxi Vil.      4.5902e-01 -1.4358e-03  5.8294e-02  1.9071e+00         0.0565
Yuanzhong Vil.   3.5726e-01 -1.5012e-03  6.0947e-02  1.4532e+00         0.1462
Yuguang Vil.     4.6208e-01 -3.4082e-03  2.0887e-01  1.0185e+00         0.3084
Yunong Vil.      5.1129e-01 -4.3902e-03  1.7772e-01  1.2232e+00         0.2212
Yuping Vil.     -2.3468e-02 -4.2255e-05  3.4786e-03 -3.9718e-01         0.6912
Yusheng Vil.    -6.1132e-01 -1.0738e-03  6.5963e-02 -2.3760e+00         0.0175
Zaixing Vil.     2.0901e-01 -5.9672e-04  2.9218e-02  1.2263e+00         0.2201
Zhangnan Vil.   -3.0502e-01 -1.6364e-03  4.9409e-02 -1.3649e+00         0.1723
Zhangsheng Vil.  1.8300e-01 -3.6105e-03  1.4627e-01  4.8794e-01         0.6256
Zhangxing Vil.   4.5197e-01 -3.6105e-03  1.2486e-01  1.2893e+00         0.1973
Zhengjue Vil.    4.6908e-01 -6.1169e-03  2.1100e-01  1.0345e+00         0.3009
Zhengqiang Vil. -6.8631e-02 -1.1437e-03  5.5969e-02 -2.8527e-01         0.7754
Zhenxing Vil.    1.2354e-03 -4.9815e-06  2.0255e-04  8.7156e-02         0.9305
Zhonghua Vil.    1.7199e+00 -1.5164e-03  7.4180e-02  6.3203e+00         0.0000
Zhonglou Vil.   -1.7286e-02 -4.4155e-04  1.7946e-02 -1.2574e-01         0.8999
Zhongxi Vil.     8.2305e-02 -6.2932e-04  1.6837e-02  6.3915e-01         0.5227
Zhongxiao Vil.   1.9188e-01 -2.6776e-03  6.4072e-02  7.6862e-01         0.4421
Zhongxing Vil.   3.7205e-01 -4.7816e-04  9.4754e-03  3.8270e+00         0.0001
Zhongzhou Vil.   4.1369e-01 -2.4000e-03  2.9687e-01  7.6366e-01         0.4451
Zhoubei Vil.     1.8039e-01 -2.0000e-03  1.6432e-01  4.4993e-01         0.6528
Zhounan Vil.     2.7417e-01 -2.0000e-03  6.9275e-02  1.0493e+00         0.2941
Zhuangjing Vil.  4.6378e-01 -1.3235e-03  6.4756e-02  1.8277e+00         0.0676
Zhuxi Vil.       4.4384e-01 -2.3171e-03  9.3993e-02  1.4553e+00         0.1456
Ziqiang Vil.     2.4236e+00 -1.3206e-02  3.9413e-01  3.8816e+00         0.0001
Zongtou Vil.     2.2813e-01 -2.3171e-03  9.3993e-02  7.5167e-01         0.4522</code></pre>
</div>
</div>
<section id="mapping-the-local-morans-i" class="level3">
<h3 class="anchored" data-anchor-id="mapping-the-local-morans-i">5.1.1 Mapping the local Moran’s I</h3>
<p>Before mapping the local Moran’s I map, the following code chunk appends the local Moran’s I dataframe (i.e.&nbsp;localMI) onto hunan SpatialPolygonDataFrame. The out SpatialPolygonDataFrame is called village_sf.localMI.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>village_sf.localMI <span class="ot">&lt;-</span> <span class="fu">cbind</span>(village_sf,localMI) <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Pr.Ii =</span> Pr.z....E.Ii..)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mapping-local-morans-i-values" class="level3">
<h3 class="anchored" data-anchor-id="mapping-local-morans-i-values">5.1.2 Mapping local Moran’s I values</h3>
<p>Using choropleth mapping functions of tmap package, we can plot the local Moran’s I values by using the code chunks below.</p>
<p>Note: Variable(s) “Ii” contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(village_sf.localMI) <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Ii"</span>, </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"RdBu"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local moran statistics"</span>) <span class="sc">+</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The positive local Moran’s I value indicates spatial clustering, suggesting that areas with similar values are close to each other on the map. Conversely, a negative local Moran’s I value indicates spatial dispersion or spatial outliers.</p>
<p>Therefore, the map visualizes the areas with positive and negative local Moran’s I values, highlighting spatial clustering and spatial dispersion, respectively. Areas with positive values indicate spatial clustering, where similar values are clustered together geographically. Conversely, areas with negative values indicate spatial dispersion, where dissimilar values are scattered across the map. Thus, the map helps identify spatial patterns of similarity and dissimilarity in the dataset.</p>
</section>
<section id="mapping-local-morans-i-p-values" class="level3">
<h3 class="anchored" data-anchor-id="mapping-local-morans-i-p-values">5.1.3 Mapping local Moran’s I p-values</h3>
<p>The choropleth shows there is evidence for both positive and negative Ii values. However, it is useful to consider the p-values for each of these values, as consider above.</p>
<p>The code chunks below produce a choropleth map of Moran’s I p-values by using functions of tmap package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(village_sf.localMI) <span class="sc">+</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Pr.Ii"</span>, </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="cn">Inf</span>),</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-Blues"</span>, </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local Moran's I p-values"</span>) <span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The thematic map reflects the spatial distribution of statistical significance regarding local Moran’s I values across various regions. Darker shades denote areas with lower p-values, indicating higher statistical significance, implying pronounced spatial clustering or outliers. Conversely, lighter-colored regions signify higher p-values, suggesting lower statistical significance and potentially indicating randomness or spatial independence.</p>
<p>In order to interpret the local moran value:</p>
<ul>
<li><p><strong>An outlier:</strong> significant and negative if location i is associated with relatively low values in surrounding locations.</p></li>
<li><p><strong>A cluster:</strong> significant and positive if location i is associated with relatively high values of the surrounding locations.</p></li>
</ul>
<p>The thematic map provides insights into the spatial distribution of dengue outbreak cases at a local level. It indicates that, across the study area, the occurrence of dengue cases exhibits spatial randomness. However, areas with higher Moran’s I p-values, representing increased spatial autocorrelation, tend to cluster together. This clustering pattern suggests that certain regions with elevated Moran’s I p-values are surrounded by neighboring areas exhibiting similar levels of spatial autocorrelation. Hence, these findings imply the presence of localized clusters within the study area, amidst an overall pattern of spatial randomness in dengue outbreak occurrences.</p>
</section>
<section id="mapping-both-local-morans-i-values-and-p-values" class="level3">
<h3 class="anchored" data-anchor-id="mapping-both-local-morans-i-values-and-p-values">5.1.4 Mapping both local Moran’s I values and p-values</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>localMI.map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(village_sf.localMI) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Ii"</span>, </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>, </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local moran statistics"</span>) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>pvalue.map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(village_sf.localMI) <span class="sc">+</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Pr.Ii"</span>, </span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="cn">Inf</span>),</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-Blues"</span>, </span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local Moran's I p-values"</span>) <span class="sc">+</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(localMI.map, pvalue.map, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="creating-a-lisa-cluster-map" class="level2">
<h2 class="anchored" data-anchor-id="creating-a-lisa-cluster-map">5.2 Creating a LISA Cluster Map</h2>
<p>The LISA Cluster Map shows the significant locations color coded by type of spatial autocorrelation. The first step before we can generate the LISA cluster map is to plot the Moran scatterplot.</p>
<section id="plotting-moran-scatterplot" class="level3">
<h3 class="anchored" data-anchor-id="plotting-moran-scatterplot">5.2.1 Plotting Moran scatterplot</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>nci <span class="ot">&lt;-</span> <span class="fu">moran.plot</span>(village_sf<span class="sc">$</span>grp_cnt, rswm_q,</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">labels=</span><span class="fu">as.character</span>(village_sf<span class="sc">$</span>VILLENG), </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">xlab=</span><span class="st">"Dengue Case Count 2023"</span>, </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ylab=</span><span class="st">"Spatially Lag Dengue Cases Count 2023"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The plot is split into 4 quadrants. The top right corner belongs to areas that have a high number of dengue cases and are surrounded by other areas that have the average level of dengue cases. These are the high-high locations.</p>
<p>For example, Chenggong Village indicates a high number of dengue cases but is surrounded by areas with a lower level of dengue cases. However, Zhonghua Village indicates a lower number of dengue cases but is surrounded by areas with a higher level of dengue outbreak cases.</p>
</section>
<section id="plotting-moran-scatterplot-with-standardised-variable" class="level3">
<h3 class="anchored" data-anchor-id="plotting-moran-scatterplot-with-standardised-variable">5.2.2 Plotting Moran scatterplot with standardised variable</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>village_sf<span class="sc">$</span>Z.grp_cnt <span class="ot">&lt;-</span> <span class="fu">scale</span>(village_sf<span class="sc">$</span>grp_cnt) <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  as.vector </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The as.vector() added to the end is to make sure that the data type we get out of this is a vector, that map neatly into out dataframe.</p>
<p>The following code chunk plots the Moran scatterplot again by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>nci2 <span class="ot">&lt;-</span> <span class="fu">moran.plot</span>(village_sf<span class="sc">$</span>Z.grp_cnt, rswm_q,</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">labels=</span><span class="fu">as.character</span>(village_sf<span class="sc">$</span>VILLENG),</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xlab=</span><span class="st">"z-Dengue Case Count 2023"</span>, </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ylab=</span><span class="st">"Spatially Lag z-Dengue Cases Count 2023"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="preparing-lisa-map-classes" class="level3">
<h3 class="anchored" data-anchor-id="preparing-lisa-map-classes">5.2.3 Preparing LISA map classes</h3>
<p>The code chunks below show the steps to prepare a LISA cluster map.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>quadrant <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">mode=</span><span class="st">"numeric"</span>,<span class="at">length=</span><span class="fu">nrow</span>(localMI))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, derives the spatially lagged variable of interest and centers the spatially lagged variable around its mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>village_sf<span class="sc">$</span>lag_grp_cnt <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(rswm_q, village_sf<span class="sc">$</span>grp_cnt)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>DV <span class="ot">&lt;-</span> village_sf<span class="sc">$</span>lag_grp_cnt <span class="sc">-</span> <span class="fu">mean</span>(village_sf<span class="sc">$</span>lag_grp_cnt)     </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is follow by centering the local Moran’s around the mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>LM_I <span class="ot">&lt;-</span> localMI[,<span class="dv">1</span>] <span class="sc">-</span> <span class="fu">mean</span>(localMI[,<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we will set a statistical significance level for the local Moran.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>signif <span class="ot">&lt;-</span> <span class="fl">0.05</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These four command lines define the low-low (1), low-high (2), high-low (3) and high-high (4) categories.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&gt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&lt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&lt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">3</span>  </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&gt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">4</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lastly, places non-significant Moran in the category 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>quadrant[localMI[,<span class="dv">5</span>]<span class="sc">&gt;</span>signif] <span class="ot">&lt;-</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>quadrant <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">mode=</span><span class="st">"numeric"</span>,<span class="at">length=</span><span class="fu">nrow</span>(localMI))</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>village_sf<span class="sc">$</span>lag_grp_cnt <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(rswm_q, village_sf<span class="sc">$</span>grp_cnt)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>DV <span class="ot">&lt;-</span> village_sf<span class="sc">$</span>lag_grp_cnt <span class="sc">-</span> <span class="fu">mean</span>(village_sf<span class="sc">$</span>lag_grp_cnt)     </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>LM_I <span class="ot">&lt;-</span> localMI[,<span class="dv">1</span>]   </span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>signif <span class="ot">&lt;-</span> <span class="fl">0.05</span>       </span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&gt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&lt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&lt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">3</span>  </span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&gt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">4</span>    </span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>quadrant[localMI[,<span class="dv">5</span>]<span class="sc">&gt;</span>signif] <span class="ot">&lt;-</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plotting-lisa-map" class="level3">
<h3 class="anchored" data-anchor-id="plotting-lisa-map">5.2.4 Plotting LISA map</h3>
<p>The following code chunk generates a thematic map displaying the spatial clustering patterns of dengue cases using Local Indicators of Spatial Association (LISA) analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>village_sf.localMI<span class="sc">$</span>quadrant <span class="ot">&lt;-</span> quadrant</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#ffffff"</span>, <span class="st">"#2c7bb6"</span>, <span class="st">"#abd9e9"</span>, <span class="st">"#fdae61"</span>, <span class="st">"#d7191c"</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>clusters <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"insignificant"</span>, <span class="st">"low-low"</span>, <span class="st">"low-high"</span>, <span class="st">"high-low"</span>, <span class="st">"high-high"</span>)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(village_sf.localMI) <span class="sc">+</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"quadrant"</span>, </span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"cat"</span>, </span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> colors[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant)))<span class="sc">+</span><span class="dv">1</span>], </span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">labels =</span> clusters[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant)))<span class="sc">+</span><span class="dv">1</span>],</span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">popup.vars =</span> <span class="fu">c</span>(<span class="st">""</span>)) <span class="sc">+</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">11</span>,<span class="dv">17</span>)) <span class="sc">+</span></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the graph, we can infer the areas that according to their classified color:</p>
<ul>
<li><p><strong>White (Insignificant)</strong>: These areas represent locations where the local spatial autocorrelation is not statistically significant.</p></li>
<li><p><strong>Blue (Low-Low)</strong>: These areas indicate clusters where low values of the variable of interest are surrounded by neighboring areas with similarly low values.</p></li>
<li><p><strong>Light Blue (Low-High)</strong>: These areas denote locations where low values of the variable of interest are surrounded by neighboring areas with high values.</p></li>
<li><p><strong>Red (High-High)</strong>: These areas represent clusters where high values of the variable of interest are surrounded by neighboring areas with similarly high values.</p></li>
</ul>
<p>The map shows that the</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>grpcnt <span class="ot">&lt;-</span> <span class="fu">qtm</span>(village_sf, <span class="st">"grp_cnt"</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>village_sf.localMI<span class="sc">$</span>quadrant <span class="ot">&lt;-</span> quadrant</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#ffffff"</span>, <span class="st">"#2c7bb6"</span>, <span class="st">"#abd9e9"</span>, <span class="st">"#fdae61"</span>, <span class="st">"#d7191c"</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>clusters <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"insignificant"</span>, <span class="st">"low-low"</span>, <span class="st">"low-high"</span>, <span class="st">"high-low"</span>, <span class="st">"high-high"</span>)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>LISAmap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(village_sf.localMI) <span class="sc">+</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"quadrant"</span>, </span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"cat"</span>, </span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> colors[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant)))<span class="sc">+</span><span class="dv">1</span>], </span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">labels =</span> clusters[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant)))<span class="sc">+</span><span class="dv">1</span>],</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>          <span class="at">popup.vars =</span> <span class="fu">c</span>(<span class="st">""</span>)) <span class="sc">+</span></span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">11</span>,<span class="dv">17</span>)) <span class="sc">+</span></span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)</span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(grpcnt, LISAmap, </span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>dengue_sf_tibble <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(dengue_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The following code chunk calculates local Moran’s I statistics for each observation using the local_moran function.</p>
</section>
</section>
<section id="computing-local-morans-i-using-local_moran-function" class="level2">
<h2 class="anchored" data-anchor-id="computing-local-morans-i-using-local_moran-function">5.3 Computing local Moran’s I (using local_moran() function)</h2>
<p>in this alternative method, the local_moran() function from the spdep package is utilized. This function directly computes the local Moran’s I statistic for each observation in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>lisa <span class="ot">&lt;-</span> wm_q <span class="sc">%&gt;%</span> </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">local_moran =</span> <span class="fu">local_moran</span>(</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>    grp_cnt, nb, wt, <span class="at">nsim =</span> <span class="dv">99</span>),</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(local_moran)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualising-local-morans-i" class="level2">
<h2 class="anchored" data-anchor-id="visualising-local-morans-i">6.2 Visualising local Moran’s I</h2>
<p>The following code chunk generates a thematic map visualizing the local Moran’s I statistics of the “Cases Count” variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"ii"</span>) <span class="sc">+</span> </span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"local Moran's I of Cases Count"</span>,</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the map, it can be observed that the areas in green (positive values) of the local Moran’s I statistic suggest spatial clustering. This suggests that neighbouring areas tend to have similar values.</p>
<p>In contrast, the areas in red/orange (negative values) suggest spatial dispersion or dissimilarity. This suggests that neighboring areas tend to have dissimilar values.</p>
<p>From the map, it can be observed that the majority of the regions fall into the range of 0-1 and 0-(-1), thus suggesting that the observations exhibit spatial randomness or no spatial clustering. However, there are more regions that exhibits spatial clustering in comparison to regions that do not.</p>
<p>The following map the p-values associated with the local Moran’s I statistic. These p-values indicate the significance of spatial autocorrelation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"p_ii_sim"</span>) <span class="sc">+</span> </span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"p-value of local Moran's I"</span>,</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The lower p-values suggest stronger evidence against the null hypothesis of spatial randomness, indicating significant spatial clustering or dispersion. Conversely, higher p-values suggest weaker evidence against the null hypothesis, indicating spatial randomness or non-significant spatial patterns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>map1 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"ii"</span>) <span class="sc">+</span> </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"local Moran's I of GDPPC"</span>,</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>map2 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"p_ii"</span>,</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="dv">1</span>),</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0.001"</span>, <span class="st">"0.01"</span>, <span class="st">"0.05"</span>, <span class="st">"Not sig"</span>)) <span class="sc">+</span> </span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"p-value of local Moran's I"</span>,</span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(map1, map2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>lisa_sig <span class="ot">&lt;-</span> lisa  <span class="sc">%&gt;%</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(p_ii <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lisa_sig) <span class="sc">+</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"mean"</span>) <span class="sc">+</span> </span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert polygons/multipolygons to points</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>village_sf<span class="sc">$</span>geometry_point <span class="ot">&lt;-</span> <span class="fu">st_centroid</span>(village_sf<span class="sc">$</span>geometry)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify the result</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(village_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 249 features and 4 fields
Active geometry column: geometry
Geometry type: GEOMETRY
Dimension:     XY
Bounding box:  xmin: 120.0627 ymin: 22.89401 xmax: 120.2925 ymax: 23.09144
Geodetic CRS:  TWD97
# A tibble: 249 × 6
   VILLENG     grp_cnt                            geometry Z.grp_cnt lag_grp_cnt
 * &lt;chr&gt;         &lt;int&gt;                       &lt;POLYGON [°]&gt;     &lt;dbl&gt;       &lt;dbl&gt;
 1 Andong Vil.      83 ((120.2164 23.0404, 120.2154 23.04…     0.156       103. 
 2 Anfu Vil.       311 ((120.1932 23.0294, 120.1929 23.02…     3.21        134. 
 3 Anhe Vil.        86 ((120.2258 23.04424, 120.2219 23.0…     0.196        76.3
 4 Ankang Vil.     102 ((120.2269 23.01413, 120.2274 23.0…     0.411       119. 
 5 Anqing Vil.     109 ((120.2113 23.04414, 120.2111 23.0…     0.505       104  
 6 Anshun Vil.      35 ((120.2136 23.05601, 120.2136 23.0…    -0.488        36.3
 7 Anxi Vil.       141 ((120.2123 23.03689, 120.212 23.03…     0.934       115. 
 8 Bao'an Vil.      33 ((120.2304 22.93544, 120.2301 22.9…    -0.515       128. 
 9 Beihua Vil.       1 ((120.2034 23.00257, 120.2032 23.0…    -0.944        45  
10 Beimen Vil.       8 ((120.2176 23.02032, 120.2173 23.0…    -0.850        95.2
# ℹ 239 more rows
# ℹ 1 more variable: geometry_point &lt;POINT [°]&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>wm_idw <span class="ot">&lt;-</span> village_sf <span class="sc">%&gt;%</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_contiguity</span>(geometry),</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">wts =</span> <span class="fu">st_inverse_distance</span>(nb, geometry_point,</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">scale =</span> <span class="dv">1</span>,</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">alpha =</span> <span class="dv">1</span>),</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>HCSA <span class="ot">&lt;-</span> wm_idw <span class="sc">%&gt;%</span> </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">local_Gi =</span> <span class="fu">local_gstar_perm</span>(</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>    grp_cnt, nb, wt, <span class="at">nsim =</span> <span class="dv">99</span>),</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(local_Gi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(HCSA) <span class="sc">+</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"gi_star"</span>) <span class="sc">+</span> </span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">8</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(HCSA) <span class="sc">+</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"p_sim"</span>) <span class="sc">+</span> </span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>map1 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(HCSA) <span class="sc">+</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"gi_star"</span>) <span class="sc">+</span> </span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Gi* of GDPPC"</span>,</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>map2 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(HCSA) <span class="sc">+</span></span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"p_value"</span>,</span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="dv">1</span>),</span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0.001"</span>, <span class="st">"0.01"</span>, <span class="st">"0.05"</span>, <span class="st">"Not sig"</span>)) <span class="sc">+</span> </span>
<span id="cb68-13"><a href="#cb68-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb68-14"><a href="#cb68-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"p-value of Gi*"</span>,</span>
<span id="cb68-15"><a href="#cb68-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span>
<span id="cb68-16"><a href="#cb68-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-17"><a href="#cb68-17" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(map1, map2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>HCSA_sig <span class="ot">&lt;-</span> HCSA  <span class="sc">%&gt;%</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(p_sim <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(HCSA) <span class="sc">+</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(HCSA_sig) <span class="sc">+</span></span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"gi_star"</span>) <span class="sc">+</span> </span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="emerging-hot-spot-analysis-sfdep-methods" class="level1">
<h1>6 Emerging Hot Spot Analysis: sfdep methods</h1>
<section id="creating-a-time-series-cube" class="level2">
<h2 class="anchored" data-anchor-id="creating-a-time-series-cube">6.1 Creating a Time Series Cube</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>grp_cnt_st <span class="ot">&lt;-</span> <span class="fu">spacetime</span>(dengue_sf_tibble, village_sf,</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">.loc_col =</span> <span class="st">"VILLENG"</span>,</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">.time_col =</span> <span class="st">"week"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is_spacetime_cube</span>(grp_cnt_st)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert polygons/multipolygons to points</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>grp_cnt_st<span class="sc">$</span>geometry_point <span class="ot">&lt;-</span> <span class="fu">st_centroid</span>(grp_cnt_st<span class="sc">$</span>geometry)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="computing-gi" class="level2">
<h2 class="anchored" data-anchor-id="computing-gi">6.2 Computing Gi*</h2>
<p>The code chunk below will be used to identify neighbors and to derive an inverse distance weights.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>grp_cnt_nb <span class="ot">&lt;-</span> grp_cnt_st <span class="sc">%&gt;%</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(<span class="st">"geometry"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">include_self</span>(<span class="fu">st_contiguity</span>(geometry)),</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">wt =</span> <span class="fu">st_inverse_distance</span>(nb, geometry_point,</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">scale =</span> <span class="dv">1</span>,</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">alpha =</span> <span class="dv">1</span>),</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_nbs</span>(<span class="st">"nb"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_wts</span>(<span class="st">"wt"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These new columns are used to manually calculate the local Gi* for each location. We can do this by grouping by week and using local_gstar_perm() of sfdep package. After which, we use unnest() to unnest gi_star column of the newly created gi_starts data.frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>gi_stars <span class="ot">&lt;-</span> grp_cnt_nb <span class="sc">%&gt;%</span> </span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(week) <span class="sc">%&gt;%</span> </span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gi_star =</span> <span class="fu">local_gstar_perm</span>(</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>    grp_cnt, nb, wt)) <span class="sc">%&gt;%</span> </span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(gi_star)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mann-kendall-test" class="level2">
<h2 class="anchored" data-anchor-id="mann-kendall-test">6.3 Mann-Kendall Test</h2>
<p>With these Gi* measures we can then evaluate each location for a trend using the Mann-Kendall test. The code chunk below uses Sanmin Vil.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>smv <span class="ot">&lt;-</span> gi_stars <span class="sc">%&gt;%</span> </span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(VILLENG <span class="sc">==</span> <span class="st">"Sanmin Vil."</span>) <span class="sc">|&gt;</span> </span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(VILLENG, week, gi_star)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> smv, </span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> week, </span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> gi_star)) <span class="sc">+</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> smv, </span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> week, </span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> gi_star)) <span class="sc">+</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplotly</span>(p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-723e923de71f27148cee" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-723e923de71f27148cee">{"x":{"data":[{"x":[31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50],"y":[-0.90822312088993984,-1.1422080442638727,-1.228868772006904,-1.0619914742622887,-1.6887534627004213,-1.6111137285398907,-1.8000400623490198,-1.9330982212037362,-2.0069634864520678,-1.5594173167916241,-2.0134815659971039,-1.51426393181024,-1.2196134614448955,-1.3963149499049905,-2.0697276193324146,-1.1452968402614374,-0.76479828048445608,-0.78214377123023393,0.94644146916249128,0.051425592670119473],"text":["week: 31<br />gi_star: -0.90822312","week: 32<br />gi_star: -1.14220804","week: 33<br />gi_star: -1.22886877","week: 34<br />gi_star: -1.06199147","week: 35<br />gi_star: -1.68875346","week: 36<br />gi_star: -1.61111373","week: 37<br />gi_star: -1.80004006","week: 38<br />gi_star: -1.93309822","week: 39<br />gi_star: -2.00696349","week: 40<br />gi_star: -1.55941732","week: 41<br />gi_star: -2.01348157","week: 42<br />gi_star: -1.51426393","week: 43<br />gi_star: -1.21961346","week: 44<br />gi_star: -1.39631495","week: 45<br />gi_star: -2.06972762","week: 46<br />gi_star: -1.14529684","week: 47<br />gi_star: -0.76479828","week: 48<br />gi_star: -0.78214377","week: 49<br />gi_star:  0.94644147","week: 50<br />gi_star:  0.05142559"],"type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(0,0,0,1)","dash":"solid"},"hoveron":"points","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":26.228310502283108,"r":7.3059360730593621,"b":40.182648401826498,"l":37.260273972602747},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[30.050000000000001,50.950000000000003],"tickmode":"array","ticktext":["35","40","45","50"],"tickvals":[35,40,45,50],"categoryorder":"array","categoryarray":["35","40","45","50"],"nticks":null,"ticks":"outside","tickcolor":"rgba(179,179,179,1)","ticklen":3.6529680365296811,"tickwidth":0.33208800332088001,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(222,222,222,1)","gridwidth":0.33208800332088001,"zeroline":false,"anchor":"y","title":{"text":"week","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-2.22053607375716,1.0972499235872366],"tickmode":"array","ticktext":["-2","-1","0","1"],"tickvals":[-2,-1,0,1],"categoryorder":"array","categoryarray":["-2","-1","0","1"],"nticks":null,"ticks":"outside","tickcolor":"rgba(179,179,179,1)","ticklen":3.6529680365296811,"tickwidth":0.33208800332088001,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(222,222,222,1)","gridwidth":0.33208800332088001,"zeroline":false,"anchor":"x","title":{"text":"gi_star","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(179,179,179,1)","width":0.66417600664176002,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"a1dc5569b8d1":{"x":{},"y":{},"type":"scatter"}},"cur_data":"a1dc5569b8d1","visdat":{"a1dc5569b8d1":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("Kendall")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>smv <span class="sc">%&gt;%</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mk =</span> <span class="fu">list</span>(</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">unclass</span>(</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>      Kendall<span class="sc">::</span><span class="fu">MannKendall</span>(gi_star)))) <span class="sc">%&gt;%</span> </span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest_wider</span>(mk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
    tau    sl     S     D  varS
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 0.179 0.284    34  190.   950</code></pre>
</div>
</div>
<p>In the above result, sl is the p-value. This result tells us that there is an upward but insignificant trend.</p>
<p>Now to replicate this for each location by using group_by() of dplyr package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>ehsa <span class="ot">&lt;-</span> gi_stars <span class="sc">%&gt;%</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(VILLENG) <span class="sc">%&gt;%</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mk =</span> <span class="fu">list</span>(</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">unclass</span>(</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>      Kendall<span class="sc">::</span><span class="fu">MannKendall</span>(gi_star)))) <span class="sc">%&gt;%</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest_wider</span>(mk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="arrange-to-show-significant-emerging-hotcold-spots" class="level2">
<h2 class="anchored" data-anchor-id="arrange-to-show-significant-emerging-hotcold-spots">6.4 Arrange to show significant emerging hot/cold spots</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>emerging <span class="ot">&lt;-</span> ehsa <span class="sc">%&gt;%</span> </span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(sl, <span class="fu">abs</span>(tau)) <span class="sc">%&gt;%</span> </span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="performing-emerging-hotspot-analysis" class="level2">
<h2 class="anchored" data-anchor-id="performing-emerging-hotspot-analysis">6.5 Performing Emerging Hotspot Analysis</h2>
<p>Lastly, to perform EHSA analysis by using emerging_hotspot_analysis() of sfdep package. It takes a spacetime object x (i.e.&nbsp;grp_cnt_st), and the quoted name of the variable of interest (i.e.&nbsp;grp_cnt) for .var argument. The k argument is used to specify the number of time lags which is set to 1 by default. Lastly, nsim map numbers of simulation to be performed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>grpcnt_st <span class="ot">&lt;-</span> grp_cnt_st[, <span class="sc">!</span><span class="fu">colnames</span>(grp_cnt_st) <span class="sc">%in%</span> <span class="st">"VILLENG"</span>, drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ehsa &lt;- emerging_hotspot_analysis(</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  x = grpcnt_st, </span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  .var = "grp_cnt", </span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  k = 1, </span></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a><span class="co">#  nsim = 99</span></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a><span class="co">#)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>note: i couldnt resolve the error here…</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>